name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0

    - uses: actions/cache@v1 
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-   

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --no-silent --base-href=./ --name="tobiaswright" --email=tobias@tobiaswright.com
